name: Generate Terminal

on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Example
      - uses: lowlighter/metrics@latest
      - with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
